# Site settings
title: Todd Lunter
email: tlunter@gmail.com
description: ""
baseurl: ""
url: "https://tlunter.com"
twitter_username: tlunter
github_username:  tlunter

# Build settings
markdown: kramdown
permalink: pretty

exclude:
  - bower_components
  - node_modules
  - vendor
  - bower.json
  - Dockerfile
  - Gemfile
  - Gemfile.lock
  - gulpfile.js
  - nginx.conf
  - package.json
  - package-lock.json

kramdown:
  input: GFM

navigation:
  - icon: home
    url: /
  - icon: archive
    url: /archive/

plugins:
  - jekyll-responsive-image

responsive_image:
  template: _includes/responsive-image.html
  auto_rotate: true
  base_path: _assets/

  output_path_format: images/resized/%{width}/%{basename}
  save_to_source: false

  strip: true

  sizes:
    - width: 1400
      quality: 100
    - width: 900
      quality: 100
